# NYAA-STATS CONFIGURATION FILE

# Grabber (main program) configuration
render:
  # Data sources

  # [Required] `level.dat` file path. Example: "/opt/minecraft/world/level.dat"
  level: data/level.dat
  # [Required] `playerdata` directory path. Example: "/opt/minecraft/world/playerdata"
  playerdata: data/playerdata
  # [Required] `stats` directory path. Example: "/opt/minecraft/world/stats"
  stats: data/stats
  # [Required] `advancements` directory path. Example: "/opt/minecraft/world/advancements"
  advancements: data/advancements
  # Whether to only process whitelisted players. Possible values:
  #   {string} - `whitelist.json` file path. Example: "/opt/minecraft/whitelist.json"
  #   (unset)  - Disable this feature (to process all reachable players)
  whitelist: whitelist.json
  # Banned UUID list. Possible values:
  #   {string} - `banned-players.json` file path. Example: "/opt/minecraft/banned-players.json"
  #   (unset)  - Disable this feature (to assume no bans)
  banned-players: banned-players.json
  # Whether to render banned players. Default value: `false`
  render-banned: false
  # [Required] Crafatar service URL, used for player avatar/skin model generating
  crafatar: https://crafatar.com
  # Crafatar for third-party yggdrasil api
  ygg-crafatar: https://user.turna.live/crafater
  #Yggdrasil API Session Server Profile URL
  ygg-profile: https://user.turna.live/api/yggdrasil/sessionserver/session/minecraft/profile

  # Output

  # [Required] Output data directory path (absolute or relative to runtime `config.yml`)
  # Example: "webroot/data"
  output: web/public/data
  # Whether to prompt confirmation to clear output directory. You may want to set `false` if you're
  # using cronjob. Possible values:
  #   `true` | (unset) - Prompt confirmation. You can choose yes or no to output directory clearing
  #   `false`          - Disable this feature (will not clear output directory)
  confirm-clear-data: true
  # [Deprecated]
  time-format: # time format on display, details http://momentjs.com/docs/#/displaying/format/
    full: dddd, MMMM Do, YYYY HH:mm:ss ZZ
    short: MMMM Do, YYYY
    compact: YYYY-M-D HH:mm:ss

# API usage configuration
api:
  # [Required] Mojang API request rate limit (N req per second)
  ratelimit: 2

# Web app configuration
web:
  # [Required] Web app title, will be displayed at page header and as window title
  title: Nyaa Stats
  # [Required] Server name, will be displayed at welcome section and page footer
  servername: Minecraft Server
  # [Required] Server homepage URL, will be displayed at welcome section
  homepage: https://minecraft.example.com
